# 에러 처리

<br/>

## try ... catch ... finally

```js
try {
  // 실행할 코드
} catch (error) {
  // try에서 에러가 발생하면 Error 객체가 전달되고 이 코드 블록이 실행된다.
} finally {
  // 에러와 상관없이 무조건 한 번 실행된다.
}
```

## Error 객체와 throw

```js
try {
  // 에러 객체를 던지면 catch 코드 블록이 실행된다.
  throw new Error('Error message');
} catch (error) {
  console.log(error);
}
```

## 사용 예

```js
function readData(user) {
  if (!user.name) {
    throw new Error('유저의 이름을 찾을 수 없음');
  }
  return user.name;
}

function processData(user) {
  let content;
  try {
    content = readData(user);
  } catch (error) {
    console.log(error);
    content = 'undefined';
  } finally {
    console.log('성공하든 실패하든 마지막으로 리소스를 정리할 수 있음!');
  }
  const result = 'Hi ' + content;
  return result;
}

let sunny = {
  name: 'Sunny',
  age: 20,
};

let hanny = {
  age: 30,
};

const result = processData(hanny);
console.log(result); // 유저의 이름을 찾을 수 없음

const result = processData(sunny);
console.log(result); // Hi Sunny
```
